function C = cauchy_def_5_13(x, n, def_src, def_tgt)
% CAUCHY_DEF_5_13 Evaluates Cauchy operator C[Gamma, Omega] for ray source and disjoint target.
%
% Syntax:
%   C = cauchy_def_5_13(x, n, def_src, def_tgt)
%
% Inputs:
%   x       - Collocation nodes on target curve Omega (length n_Omega)
%   n       - Number of collocation nodes on source ray Gamma
%   def_src - Source ray definition struct (M_inf = +/- 1)
%   def_tgt - Disjoint target contour definition struct
%
% Outputs:
%   C       - Discrete Cauchy transform matrix of size n_Omega x n
%
% Description:
%   Evaluates the Cauchy interaction from an unbounded ray to an exterior disjoint
%   contour by expanding the basis dimension to m = n + 1, applying the conformal
%   Joukowsky map, slicing out the column at infinity, and subtracting the boundary
%   rank-one term generated by Algorithm 5.4.
%
% References:
%   S. Olver, Numer. Math. (2012), Definition 5.13.

    m = n + 1; % Extended basis dimension including infinity

    % 1. Restore point at infinity for target ray prior to evaluation
    if strcmp(def_tgt.type, 'ray')
        if isfield(def_tgt, 'direction') && strcmp(def_tgt.direction, 'backward')
            x_tgt_full = [-1; x(:)];
        else
            x_tgt_full = [x(:); 1];
        end
    else
        x_tgt_full = x(:);
    end

    % 2. Map target nodes to complex coordinates and project to source frame w
    pts_tgt = curve_mapping(def_tgt, x_tgt_full);
    z_omega = pts_tgt{1};
    w = forward_map(def_src, z_omega);

    % 3. Evaluate exterior Joukowsky basis (strictly |z_psi| < 1)
    z_psi = w - sqrt(w - 1) .* sqrt(1 + w);
    Psi_z = psi_row(z_psi, m); % Size: n_Omega x m

    x_I = flipud(cos(pi * (0:m-1)' / (m - 1)));
    F = inv(cheby(x_I, m));
    C_base = Psi_z * F;

    % 4. Identify M_inf and retrieve boundary limit vector mu via Algorithm 5.4
    if strcmp(def_src.direction, 'forward')
        M_inf = 1;
    else
        M_inf = -1;
    end
    [mu_L, mu_R] = algorithm_5_4(m);

    % 5. Perform column slicing and apply rank-one correction
    if M_inf == -1
        C_sliced = C_base(:, 2:m);
        F_gamma  = F(:, 2:m);
        mu_vec   = mu_L;
    else
        C_sliced = C_base(:, 1:n);
        F_gamma  = F(:, 1:n);
        mu_vec   = mu_R;
    end

    sub = ones(size(C_sliced, 1), 1) * (mu_vec * F_gamma);
    C = C_sliced - sub;
end